# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/amstee"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Twitter"
url = "https://www.linkedin.com/in/jeremy-barneron/"

[social.params]
icon = "brand-linkedin"
